/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package optimizaciónag.GUI;

import CustomOutputStream.CustomOutputStream;
import GraficadorAG.FunctionParser;
import GraficadorAG.GraficadorFunciones;
import java.awt.Color;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import static java.lang.System.out;
import optimizaciónag.ConfiguracionAG;
import org.math.plot.Plot2DPanel;

/**
 *
 * @author carlos
 */
public class GUIAGD extends javax.swing.JFrame {

    /**
     * Creates new form GUIAGD
     */
    
    int xMouse, yMouse;
    final Plot2DPanel grafica= new Plot2DPanel();

            
    public GUIAGD() {
        
        initComponents();
        grafica.setBounds(400,35,400,300);
        Background.add(grafica,new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 35, 400, 300));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Background = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Funcion1 = new javax.swing.JLabel();
        Funcion2 = new javax.swing.JLabel();
        Funcion3 = new javax.swing.JLabel();
        Funcion4 = new javax.swing.JLabel();
        Funcion5 = new javax.swing.JLabel();
        Funcion6 = new javax.swing.JLabel();
        Funcion7 = new javax.swing.JLabel();
        Funcion8 = new javax.swing.JLabel();
        Funcion9 = new javax.swing.JLabel();
        Funcion10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(200, 200));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setFont(new java.awt.Font("Roboto Thin", 3, 12)); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextArea2ComponentAdded(evt);
            }
        });
        jTextArea2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextArea2InputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 368, 410, 170));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setToolTipText("");
        Background.setFont(new java.awt.Font("Nimbus Sans", 2, 12)); // NOI18N
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nimbus Sans", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("OPTIMIZACIÓN CON AGENTES GENÉTICOS");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 380, 40));

        jLabel3.setFont(new java.awt.Font("Nimbus Sans", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Función a optimizar:");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 170, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimizaciónAG/img/calculadora.png"))); // NOI18N
        Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 30, 30));

        jLabel5.setFont(new java.awt.Font("Nimbus Sans", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimizaciónAG/img/output.png"))); // NOI18N
        jLabel5.setText("Output");
        Background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 140, 60));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        Background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 340, 10));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        Background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 10));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        Background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 420, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setToolTipText("");
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimizaciónAG/img/cerrar.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimizaciónAG/img/investigar.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("App Algoritmos Genéticos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 541, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        Funcion1.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion1.setForeground(new java.awt.Color(153, 153, 153));
        Funcion1.setText("log(sqrt(3x+1))-log(2x-3)-1+log(5)");
        Funcion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion1MouseExited(evt);
            }
        });
        Background.add(Funcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        Funcion2.setBackground(new java.awt.Color(255, 255, 255));
        Funcion2.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion2.setForeground(new java.awt.Color(153, 153, 153));
        Funcion2.setText("(x²-5x+9)lg(2)+log(125)-3");
        Funcion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion2MouseExited(evt);
            }
        });
        Background.add(Funcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        Funcion3.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion3.setForeground(new java.awt.Color(153, 153, 153));
        Funcion3.setText("log(2^(2-x))^(2+x)+log(1250)-4");
        Funcion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion3MouseExited(evt);
            }
        });
        Background.add(Funcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        Funcion4.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion4.setForeground(new java.awt.Color(153, 153, 153));
        Funcion4.setText("(log(2)+lg(11-x²))/log(5-x)-2");
        Funcion4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion4MouseExited(evt);
            }
        });
        Background.add(Funcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        Funcion5.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion5.setForeground(new java.awt.Color(153, 153, 153));
        Funcion5.setText("(x²-4x+7)log(5)+log(16)-4");
        Funcion5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion5MouseExited(evt);
            }
        });
        Background.add(Funcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        Funcion6.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion6.setForeground(new java.awt.Color(153, 153, 153));
        Funcion6.setText("log(x+sqrt(x²-1))+log(x+sqrt(x²-1))");
        Funcion6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion6MouseExited(evt);
            }
        });
        Background.add(Funcion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        Funcion7.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion7.setForeground(new java.awt.Color(153, 153, 153));
        Funcion7.setText("3log(x)-log(32)-log(x/2)");
        Funcion7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion7MouseExited(evt);
            }
        });
        Background.add(Funcion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        Funcion8.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion8.setForeground(new java.awt.Color(153, 153, 153));
        Funcion8.setText("log_2(x*log_x(2x)*log_(2x)(y))-log_x(x²)");
        Funcion8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion8MouseExited(evt);
            }
        });
        Background.add(Funcion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        Funcion9.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion9.setForeground(new java.awt.Color(153, 153, 153));
        Funcion9.setText("5log(x/2)+log(x/3)-3log(x)+log(32/9)");
        Funcion9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion9MouseExited(evt);
            }
        });
        Background.add(Funcion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        Funcion10.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        Funcion10.setForeground(new java.awt.Color(153, 153, 153));
        Funcion10.setText("2log(x)-3-log(x/10)");
        Funcion10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Funcion10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Funcion10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Funcion10MouseExited(evt);
            }
        });
        Background.add(Funcion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimizaciónAG/img/adn.png"))); // NOI18N
        Background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/optimizaciónAG/img/adn1.png"))); // NOI18N
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -30, 290, 500));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jPanel3MouseEntered

    private void Funcion2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion2MouseEntered
        // TODO add your handling code here:
        Funcion2.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion2MouseEntered

    private void Funcion2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion2MouseExited
        // TODO add your handling code here:
        Funcion2.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion2MouseExited

    private void Funcion3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion3MouseEntered
        // TODO add your handling code here:
        Funcion3.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion3MouseEntered

    private void Funcion3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion3MouseExited
        Funcion3.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion3MouseExited

    private void Funcion4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion4MouseEntered
        Funcion4.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion4MouseEntered

    private void Funcion4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion4MouseExited
        Funcion4.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion4MouseExited

    private void Funcion5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion5MouseEntered
        Funcion5.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion5MouseEntered

    private void Funcion5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion5MouseExited
        Funcion5.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion5MouseExited

    private void Funcion6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion6MouseEntered
        Funcion6.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion6MouseEntered

    private void Funcion6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion6MouseExited
        Funcion6.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion6MouseExited

    private void Funcion7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion7MouseEntered
        Funcion7.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion7MouseEntered

    private void Funcion7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion7MouseExited
        Funcion7.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion7MouseExited

    private void Funcion8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion8MouseEntered
        Funcion8.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion8MouseEntered

    private void Funcion8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion8MouseExited
        Funcion8.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion8MouseExited

    private void Funcion9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion9MouseEntered
        Funcion9.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion9MouseEntered

    private void Funcion9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion9MouseExited
        Funcion9.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion9MouseExited

    private void Funcion10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion10MouseEntered
        Funcion10.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion10MouseEntered

    private void Funcion10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion10MouseExited
        Funcion10.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion10MouseExited

    private void Funcion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion1MouseExited
        Funcion1.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_Funcion1MouseExited

    private void Funcion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion1MouseEntered
        Funcion1.setForeground(new Color (89,172,183));
    }//GEN-LAST:event_Funcion1MouseEntered

    private void Funcion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion2MouseClicked
        // TODO add your handling code here:
        PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(1);
        FunctionParser funcion= new FunctionParser("(x^2-5x+9)log(2)+log(125)-3");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, -5, 5, 10, 1e-6);
        double [] x= new double[200];
        double [] y= new double [200];
        double xi= -5 -10;
        for(int i=0;i<200;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);
    }//GEN-LAST:event_Funcion2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        jLabel8.setBackground(Color.red);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        jLabel8.setBackground(Color.white);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jTextArea2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextArea2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea2InputMethodTextChanged

    private void jTextArea2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextArea2ComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextArea2ComponentAdded

    private void Funcion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion3MouseClicked
        // TODO add your handling code here:
                PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(2);
        FunctionParser funcion= new FunctionParser("log(2^(2-x))^(2+x)+log(1250)-4");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, -5, 5, 10, 1e-6);
        double [] x= new double[170];
        double [] y= new double [170];
        double xi= -5 -10;
        for(int i=0;i<170;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);
    }//GEN-LAST:event_Funcion3MouseClicked

    private void Funcion4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion4MouseClicked
        // TODO add your handling code here:
                PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(3);
        FunctionParser funcion= new FunctionParser("((log(2)+log(11-x^2))/(log(5-x)))-2");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, -3, 3, 10, 1e-10);
        double [] x= new double[64];
        double [] y= new double [64];
        double xi= -3 ;
        for(int i=0;i<64;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);        
        
    }//GEN-LAST:event_Funcion4MouseClicked

    private void Funcion5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion5MouseClicked
                PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(4);
        FunctionParser funcion= new FunctionParser("(x^2-4x+7)log(5)+log(16)-4");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, -5, 5, 10, 1e-6);
        double [] x= new double[300];
        double [] y= new double [300];
        double xi= -5 -10;
        for(int i=0;i<300;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);
    }//GEN-LAST:event_Funcion5MouseClicked

    private void Funcion6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion6MouseClicked
                PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(5);
        FunctionParser funcion= new FunctionParser("log(x+sqrt(x^2-1))+log(x+sqrt(x^2-1))");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, 1, 5, 10, 1e-6);
        double [] x= new double[200];
        double [] y= new double [200];
        double xi= 1+5;
        for(int i=0;i<200;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);
    }//GEN-LAST:event_Funcion6MouseClicked

    private void Funcion7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion7MouseClicked
                PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(6);
        FunctionParser funcion= new FunctionParser("3log(x)-log(32)-log(x/2)");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, 1, 10, 10, 1e-6);
        double [] x= new double[200];
        double [] y= new double [200];
        double xi= 0.1;
        for(int i=0;i<200;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);
    }//GEN-LAST:event_Funcion7MouseClicked

    private void Funcion8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion8MouseClicked
                PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(7);
        FunctionParser funcion= new FunctionParser("(log(x)/log(2))-2");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, 1, 5, 10, 1e-6);
        double [] x= new double[200];
        double [] y= new double [200];
        double xi= 1;
        for(int i=0;i<200;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);
    }//GEN-LAST:event_Funcion8MouseClicked

    private void Funcion9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion9MouseClicked
                PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(8);
        FunctionParser funcion= new FunctionParser("5log(x/2)+log(x/3)-3log(x)+log(32/9)");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, 1, 5, 10, 1e-6);
        double [] x= new double[200];
        double [] y= new double [200];
        double xi= 0.1;
        for(int i=0;i<200;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);
    }//GEN-LAST:event_Funcion9MouseClicked

    private void Funcion10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion10MouseClicked
                PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(9);
        FunctionParser funcion= new FunctionParser("2log(x)-3-log(x/10)");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, 1, 5, 10, 1e-6);
        double [] x= new double[200];
        double [] y= new double [200];
        double xi= 0.1;
        for(int i=0;i<200;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);
    }//GEN-LAST:event_Funcion10MouseClicked

    private void Funcion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Funcion1MouseClicked
                PrintStream printStream = new PrintStream(new CustomOutputStream(jTextArea2));
        System.setOut(printStream);
        System.setErr(printStream);
         new ConfiguracionAG().ConfiguracionAG(10);
        FunctionParser funcion= new FunctionParser("log(sqrt(3x+1))-log(2x-3)-1+log(5)");
        GraficadorFunciones nuevograph = new GraficadorFunciones();
        double r= nuevograph.ParametrosGrafica(funcion, 2, 5, 10, 1e-6);
        double [] x= new double[200];
        double [] y= new double [200];
        double xi= 1.6;
        for(int i=0;i<200;i++){
            x[i]=xi+i*0.1;
            y[i]=funcion.FunctionEvaluator(x[i]);    
        }
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot("f(x)", x, y);
    }//GEN-LAST:event_Funcion1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAGD().setVisible(true);
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Funcion1;
    private javax.swing.JLabel Funcion10;
    private javax.swing.JLabel Funcion2;
    private javax.swing.JLabel Funcion3;
    private javax.swing.JLabel Funcion4;
    private javax.swing.JLabel Funcion5;
    private javax.swing.JLabel Funcion6;
    private javax.swing.JLabel Funcion7;
    private javax.swing.JLabel Funcion8;
    private javax.swing.JLabel Funcion9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
